# Generated by Django 5.2.4 on 2025-09-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analysis', '0003_alter_financialratio_ratio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialratio',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год расчета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='document_type',
            field=models.CharField(choices=[('balance', 'Бухгалтерский баланс'), ('profit_loss', 'Отчет о финансовых результатах'), ('cash_flow', 'Отчет о движении денежных средств')], max_length=20),
        ),
        migrations.CreateModel(
            name='BalanceSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код строки')),
                ('name', models.TextField(verbose_name='Наименование показателя')),
                ('value_2022', models.FloatField(blank=True, null=True)),
                ('value_2023', models.FloatField(blank=True, null=True)),
                ('value_2024', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analysis.financialdocument')),
            ],
            options={
                'unique_together': {('document', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код строки')),
                ('name', models.TextField(verbose_name='Наименование показателя')),
                ('value_2023', models.FloatField(blank=True, null=True)),
                ('value_2024', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analysis.financialdocument')),
            ],
            options={
                'unique_together': {('document', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProfitLossData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код строки')),
                ('name', models.TextField(verbose_name='Наименование показателя')),
                ('value_2023', models.FloatField(blank=True, null=True)),
                ('value_2024', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_analysis.financialdocument')),
            ],
            options={
                'unique_together': {('document', 'code')},
            },
        ),
    ]
