# Generated by Django 5.2.4 on 2025-07-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='description',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='image',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='title',
            new_name='title2',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='url',
            new_name='url2',
        ),
    ]
